# brynhild-deno-plugin
#
# Sandboxed compute tools using Deno + Pyodide (WebAssembly)
# See README.md for setup and usage.
#
# NOTE: This plugin requires Deno >=2.0 to be installed separately.
# Install from: https://deno.land/manual/getting_started/installation

name: deno-sandbox
version: 0.1.0
description: >
  Sandboxed Python execution using Deno + Pyodide (WebAssembly).
  All dependencies are vendored for air-gapped/enterprise deployment.

author: Brynhild Team
license: MIT

brynhild_version: ">=0.2.0"

tools:
  - python_sandbox
